apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: 2048
  template:
    metadata:
      labels:
        app: 2048
    spec:
      containers:
      - name: 2048-container
        image: allenaira/2048:latest 
        ports:
        - containerPort: 80
